# Gradient and Hessian 
**Mateo Serrato Ascencio**

Make a python script that computes the gradient and the hessian of the following functions:




# FUNCTIONS: 

In [2]:
import numpy as np

def gradient(f, x, h=1e-5):
    """Función para calcular el gradiente usando la definición de
    la derivada númerica
    """
    n = len(x) #Dimension del espacio (en nuestro caso es 2)
    grad = np.zeros(n) #Inicializamos el vector del gradiente en cero

    """
    Hacemos un ciclo en donde le vamos sumando un valor muy pequeño a cada
    componente del vector, y luego se lo restamos para ver como varía esa función
    con respecto a cada componente del vector 
    """
    for i in range(n):  
        xf, xb = x.copy(), x.copy()
        xf[i] += h
        xb[i] -= h
        grad[i] = (f(xf) - f(xb)) / (2 * h)
    return grad

def hessian(f, x, h=1e-5):
    """Aplicamos la misma lógica pero para calcular las segundas derivadas
    que corresponden a la matriz Hessiana"""
    n = len(x)
    H = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            xpp, xpm, xmp, xmm = x.copy(), x.copy(), x.copy(), x.copy()
            xpp[i] += h; xpp[j] += h
            xpm[i] += h; xpm[j] -= h
            xmp[i] -= h; xmp[j] += h
            xmm[i] -= h; xmm[j] -= h
            H[i, j] = (f(xpp) - f(xpm) - f(xmp) + f(xmm)) / (4 * h**2)
    return H


x = np.array([1.0, 1.0])  # punto de evaluación

 1.

$$
f_1(x_1, x_2) = (a - x_1)^2 + b (x_2 - x_1^2)^2,
\quad a = 1,\; b = 100
$$

In [3]:
a, b = 1, 100
f1 = lambda x: (a - x[0])**2 + b * (x[1] - x[0]**2)**2

print("f1:")
print("  Gradiente:", gradient(f1, x))
print("  Hessiana:\n", hessian(f1, x))

f1:
  Gradiente: [4.00000478e-08 1.11022527e-14]
  Hessiana:
 [[ 802.00000008 -400.        ]
 [-400.          200.        ]]



 2.

$$
f_2(x_1, x_2) = (x_1 + 2x_2 - 7)^2 + (2x_1 + x_2 - 5)^2
$$

 

In [4]:
f2 = lambda x: (x[0] + 2*x[1] - 7)**2 + (2*x[0] + x[1] - 5)**2

print("f2:")
print("  Gradiente:", gradient(f2, x))
print("  Hessiana:\n", hessian(f2, x))

f2:
  Gradiente: [-16. -20.]
  Hessiana:
 [[10.00000083  8.00000066]
 [ 8.00000066 10.00000083]]


3.

$$
f_3(x_1, x_2) =
(1.5 - x_1 + x_1 x_2)^2
+ (2.25 - x_1 + x_1 x_2^2)^2
+ (2.625 - x_1 + x_1 x_2^3)^2
$$



In [5]:
f3 = lambda x: (
    (1.5   - x[0] + x[0]*x[1]  )**2 +
    (2.25  - x[0] + x[0]*x[1]**2)**2 +
    (2.625 - x[0] + x[0]*x[1]**3)**2
)

print("f3:")
print("  Gradiente:", gradient(f3, x))
print("  Hessiana:\n", hessian(f3, x))

f3:
  Gradiente: [ 0.   27.75]
  Hessiana:
 [[ 0.         27.75000674]
 [27.75000674 68.50001455]]


4.

$$
f_4(x_1, x_2) =
0.26(x_1^2 + x_2^2) - 0.48 x_1 x_2
$$



In [6]:
f4 = lambda x: 0.26*(x[0]**2 + x[1]**2) - 0.48*x[0]*x[1]

print("f4:")
print("  Gradiente:", gradient(f4, x))
print("  Hessiana:\n", hessian(f4, x))

f4:
  Gradiente: [0.04 0.04]
  Hessiana:
 [[ 0.52000015 -0.47999937]
 [-0.47999937  0.52000015]]


 5.

$$
f_5(x_1, x_2) =
10 \cdot 2 +
\sum_{i=1}^{2}
\left(
x_i^2 - 10 \cos(2\pi x_i)
\right)
$$

In [7]:
f5 = lambda x: 10*2 + np.sum(x**2 - 10*np.cos(2*np.pi*x))

print("f5:")
print("  Gradiente:", gradient(f5, x))
print("  Hessiana:\n", hessian(f5, x))

f5:
  Gradiente: [2. 2.]
  Hessiana:
 [[396.78417885   0.        ]
 [  0.         396.78417885]]
